DROP DATABASE IF EXISTS DotaBaseDB;

CREATE DATABASE DotaBaseDB;

CREATE TABLE DotaBaseDB.Users (
    UserID int(11) NOT NULL AUTO_INCREMENT,
    Username varchar(45),
    UserPassword varchar(90),
    EmailAddress varchar(40),
    PRIMARY KEY (UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Heroes (
    HeroID int(11) NOT NULL AUTO_INCREMENT,
    HeroName varchar(40),
    HeroIconLink varchar(255),
    HeroAttribute varchar(20),
    HeroRole varchar(15),
    HeroLane1 varchar(15),
    HeroLane2 varchar(15),
    PRIMARY KEY (HeroID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Abilities (
    AbilityID int (11) NOT NULL AUTO_INCREMENT,
    HeroID int (11),
    AbilityName varchar(30),
    AbilityIconLink varchar(255),
    PRIMARY KEY (AbilityID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.AbilityInfo (
    AbilityInfoID int(11) NOT NULL AUTO_INCREMENT,
    AbilityID int(11),
    UserID int(11),
    AbilityUserInfo TEXT,
    AbilityUpVote int(11),
    AbilityDownVote int(11),
    PRIMARY KEY (AbilityInfoID),
    FOREIGN KEY (AbilityID) REFERENCES Abilities(AbilityID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.CountersTo (
    CounterID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    CounterUserInfo TEXT,
    CounterUpVote int(11),
    CounterDownVote int(11),
    PRIMARY KEY (CounterID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.CounteredBy (
    CounteredID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    CounteredUserInfo TEXT,
    CounteredUpVote int(11),
    CounteredDownVoter int(11),
    PRIMARY KEY (CounteredID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Items (
    ItemID int(11) NOT NULL AUTO_INCREMENT,
    ItemName varchar(30),
    ItemIconLink varchar(255),
    PRIMARY KEY (ItemID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.ItemInfo (
    ItemInfoID int(11) NOT NULL AUTO_INCREMENT,
    ItemID int(11),
    UserID int(11),
    ItemUserInfo TEXT,
    ItemUpVote int(11),
    ItemDownVote int(11),
    PRIMARY KEY (ItemInfoID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.HeroItems (
    HeroItem int(11),
    ItemID int(11),
    HeroItemUserInfo TEXT,
    HeroItemUpVote int(11),
    HeroItemDownVote int(11),
    PRIMARY KEY (HeroItem),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
);

CREATE TABLE DotaBaseDB.Disscussion (
    LogID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    LogText TEXT,
    Upvote int(11),
    DownVote int(11),
    PRIMARY KEY (LogID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Clips (
    ClipID int(11),
    HeroID int(11),
    UserID int(11),
    ClipUpVote int(11),
    ClipDownVote int(11),
    PRIMARY KEY (ClipID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- INSERT HEROES INTO DATABASE
INSERT INTO DotaBaseDB.Heroes (HeroName, HeroIconLink, HeroAttribute, HeroRole, HeroLane1, HeroLane2)
VALUES
('abaddon','static/images/heroes/abaddon.png','Strength','Core','Off Lane','Safe Lane'),
('alchemist','static/images/heroes/alchemist.png','Strength','Core','Mid Lane','Safe Lane'),
('ancient-apparition','static/images/heroes/ancient_apparition.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('anti-mage','static/images/heroes/antimage.png','Agility','Core','Safe Lane', ''),
('arc-warden','static/images/heroes/arc_warden.png','Agility','Core','Mid Lane', 'Safe Lane'),
('axe','static/images/heroes/axe.png','Strength','Core','Off Lane', ''),
('bane','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('batrider','x','Intelligence','Support','Safe Lane', 'Mid Lane'),
('beastmaster','x','Strength','Core','Off Lane', ''),
('bloodseeker','x','Agility','Core','Safe Lane', 'Off Lane'),
('bounty-hunter','x','Agility','Core','Off Lane', ''),
('brewmaster','x','Strength','Core','Off Lane', 'Mid Lane'),
('bristleback','x','Strength','Core','Off Lane', ''),
('broodmother','x','Agility','Core','Mid Lane', 'Off Lane'),
('centaur-warrunner','x','Strength','Core','Off Lane', ''),
('chaos-knight','x','Strength','Core','Safe Lane', 'Off Lane'),
('chen','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('clinkz','x','Agility','Core','Safe Lane', 'Mid Lane'),
('clockwerk','x','Strength','Core','Off Lane', 'Safe Lane'),
('crystal-maiden','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('dark-seer','x','Intelligence','Support','Off Lane', ''),
('dark-willow','x','Intelligence','Support','Off Lane', 'Safe Lane'),
('dawnbreaker','x','Strength','Support','Off Lane', ''),
('dazzle','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('death-prophet','x','Intelligence','Core','Mid Lane', 'Off Lane'),
('disruptor','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('doom','x','Strength','Core','Off Lane', ''),
('dragon-knight','x','Strength','Core','Off Lane', 'Mid Lane'),
('drow-ranger','x','Agility','Core','Safe Lane', 'Mid Lane'),
('earth-spirit','x','Strength','Support','Off Lane', 'Safe Lane'),
('earthshaker','x','Strength','Support','Off Lane', 'Safe Lane'),
('elder-titan','x','Strength','Support','Off Lane', 'Safe Lane'),
('ember-spirit','x','Agility','Core','Mid Lane', 'Safe Lane'),
('enchantress','x','Intelligence','Support','Off Lane', 'Safe Lane'),
('enigma','x','Intelligence','Core','Off Lane', ''),
('faceless-void','x','Agility','Core','Safe Lane', 'Off Lane'),
('grimstroke','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('gyrocopter','x','Agility','Core','Safe Lane', 'Off Lane'),
('hoodwink','x','Agility','Support','Off Lane', 'Safe Lane'),
('huskar','x','Strength','Core','Mid Lane', 'Safe Lane'),
('invoker','x','Intelligence','Core','Mid Lane', ''),
('io','x','Strength','Support','Safe Lane', 'Off Lane'),
('jakiro','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('juggernaut','x','Agility','Core','Safe Lane', ''),
('keeper-of-the-light','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('kunkka','x','Strength','Core','Mid Lane', 'Safe Lane'),
('legion-commander','x','Strength','Core','Off Lane', 'Safe Lane'),
('leshrac','x','Intelligence','Core','Mid Lane', 'Off Lane'),
('lich','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('lifestealer','x','Strength','Core','Safe Lane', ''),
('lina','x','Intelligence','Core','Mid Lane', 'Off Lane'),
('lion','x','Intelligence','Support','Safe Lane', 'Off Lane'),
('lone-druid','x','Agility','Core','Off Lane', 'Safe Lane'),
('luna','x','Agility','Core','Safe Lane', 'Off Lane'),
('lycan','x','Strength','Core','Safe Lane', 'Off Lane'),
('magnus','x','Strength','Support','Off Lane', 'Mid Lane'),
('marci','x','Strength','Core','Off Lane', 'Safe Lane'),
('mars','x','Strength','Core','Off Lane', ''),
('medusa','x','Agility','Core','Safe Lane', 'Mid Lane'),
('meepo','x','Agility','Core','Mid Lane', ''),
('mirana','x','Agility','Support','Off Lane', 'Mid Lane'),
('monkey-king','x','Agility','Core','Safe Lane', 'Mid Lane'),
('morphling','x','Agility','Core','Safe Lane', 'Mid Lane'),
('naga-siren','x','Agility','Core','Safe Lane', ''),
("natures-prophet",'x','Intelligence','Core','Off Lane', ''),
('necrophos','x','Intelligence','Core','Off Lane', 'Mid Lane'),
('night-stalker','x','Strength','Core','Off Lane', ''),
('nyx-assassin','x','Agility','Support','Off Lane', 'Safe Lane'),
('ogre-magi','x','Strength','Support','Safe Lane', 'Off Lane'),
('omniknight','x','Strength','Support','Safe Lane', 'Off Lane'),
('oracle','x','Intelligence','Support','Safe Lane', ''),
('outworld-destroyer','x','Intelligence','Core','Mid Lane', ''),
('pangolier','x','Agility','Core','Off Lane', ''),
('phantom-assassin','x','Agility','Core','Safe Lane','Mid Lane'),
('phantom-lancer','x','Agility','Core','Safe Lane', ''),
('phoenix','x','Strength','Support','Off Lane','Safe Lane'),
('primal-beast','x','Strength','Support','Off Lane','Safe Lane'),
('puck','x','Intelligence','Core','Mid Lane','Off Lane'),
('pudge','x','Strength','Core','Off Lane','Mid Lane'),
('pugna','x','Intelligence','Support','Off Lane','Mid Lane'),
('queen-of-pain','x','Intelligence','Core','Mid Lane',''),
('razor','x','Agility','Core','Mid Lane','Off Lane'),
('riki','x','Agility','Core','Off Lane','Safe Lane'),
('rubick','x','Intelligence','Support','Safe Lane','Off Lane'),
('sand-king','x','Strength','Core','Off Lane',''),
('shadow-demon','x','Intelligence','Support','Safe Lane','Off Lane'),
('shadow-fiend','x','Agility','Core','Mid Lane',''),
('shadow-shaman','x','Intelligence','Support','Safe Lane','Off Lane'),
('silencer','x','Intelligence','Support','Safe Lane','Off Lane'),
('skywrath-mage','x','Intelligence','Support','Off Lane','Safe Lane'),
('slardar','x','Strength','Core','Off Lane','Safe Lane'),
('slark','x','Agility','Core','Safe Lane',''),
('snapfire','x','Strength','Support','Off Lane','Safe Lane'),
('sniper','x','Agility','Core','Mid Lane','Safe Lane'),
('spectre','x','Agility','Core','Safe Lane',''),
('spirit-breaker','x','Strength','Core','Off Lane',''),
('storm-spirit','x','Intelligence','Core','Mid Lane',''),
('sven','x','Strength','Core','Safe Lane',''),
('techies','x','Intelligence','Support','Off Lane',''),
('templar-assassin','x','Agility','Core','Mid Lane',''),
('terrorblade','x','Agility','Core','Safe Lane',''),
('tidehunter','x','Strength','Core','Off Lane',''),
('timbersaw','x','Strength','Core','Off Lane',''),
('tinker','x','Intelligence','Core','Mid Lane',''),
('tiny','x','Strength','Core','Off Lane','Mid Lane'),
('treant-protector','x','Strength','Support','Safe Lane','Off Lane'),
('troll-warlord','x','Agility','Core','Safe Lane',''),
('tusk','x','Strength','Core','Off Lane','Safe Lane'),
('underlord','x','Strength','Core','Off Lane',''),
('undying','x','Strength','Support','Off Lane','Safe Lane'),
('ursa','x','Agility','Core','Safe Lane',''),
('vengeful-spirit','x','Agility','Support','Safe Lane','Off Lane'),
('venomancer','x','Agility','Support','Off Lane','Safe Lane'),
('viper','x','Agility','Core','Mid Lane','Off Lane'),
('visage','x','Intelligence','Core','Mid Lane','Safe Lane'),
('void-spirit','x','Intelligence','Core','Mid Lane','Off Lane'),
('warlock','x','Intelligence','Support','Safe Lane','Off Lane'),
('weaver','x','Agility','Core','Off Lane','Safe Lane'),
('windranger','x','Intelligence','Core','Off Lane','Mid Lane'),
('winter-wyvern','x','Intelligence','Support','Safe Lane','Off Lane'),
('witch-doctor','x','Intelligence','Support','Safe Lane','Off Lane'),
('wraith-king','x','Strength','Core','Safe Lane','Off Lane'),
('zeus','x','Intelligence','Core','Mid Lane','Off Lane');

-- INSERT ITEMS INTO DATABASE
INSERT INTO DotaBaseDB.Items (ItemName, ItemIconLink)
VALUES
('Abysal Blade','x'),
('Agies of the Immortal','x'),
('Aeon Disk','x'),
('Aether Lens','x'),
("Aghanim's Scepter",'x'),
("Aghanim's Shard",'x'),
('Apex','x'),
('Arcane Blink','x'),
('Arcane Boots','x'),
('Arcane Ring','x'),
("Arcanist's Armor",'x'),
('Armelt of Mordiggian','x'),
("Ascetic's Cap",'x'),
('Assult Cuirass','x'),
('Ballista','x'),
('Band of Elvenskin','x'),
('Battle Fury','x'),
('Belt of Strength','x'),
('Black King Bar','x'),
('Blade Mail','x'),
('Blade of Alacrity','x'),
('Blades of Attack','x'),
('Blast Rig','x'),
('Blight Stone','x'),
('Blink Dagger','x'),
('Blitz Knuckles','x'),
('Bloodstone','x'),
('Bloodthorn','x'),
('Book of Shadows','x'),
('Book of the Dead','x'),
('Boots of Bearing','x'),
('Boots of Speed','x'),
('Boots of Travel','x'),
('Boots of Travel 2','x'),
('Bottle','x'),
('Bracer','x'),
("Brigand's Blade",'x'),
('Broadsword','x'),
('Broom Handle','x'),
('Buckler','x'),
('Bullwhip','x'),
('Butterfly','x'),
('Ceremonial Robe','x'),
('Chainmail','x'),
('Chipped Vest','x'),
('Circlet','x'),
('Claymore','x'),
('Cloak','x'),
('Cloak of Flames','x'),
('Clumsy Net','x'),
('Craggy Coat','x'),
('Crimson Guard','x'),
('Crown','x'),
('Crystalys','x'),
('Daedalus','x'),
('Dagon 1','x'),
('Dagon 2','x'),
('Dagon 3','x'),
('Dagon 4','x'),
('Dagon 5','x'),
('Demon Edge','x'),
('Desolator','x'),
('Desolator 2','x'),
('Diffusal Blade','x'),
('Divine Rapier','x'),
('Dragon Lance','x'),
('Drum of Endurance','x'),
('Dust of Appearance','x'),
('Eaglesong','x'),
('Echo Sabre','x'),
('Elven Tunic','x'),
('Enchanted Quiver','x'),
('Energy Booster','x'),
('Essence Ring','x'),
('Eternal Shroud','x'),
('Etheral Blade','x'),
("Eul's Scepter of Divinity",'x'),
('Ex Machina','x'),
('Eye of Skadi','x'),
('Fae Grenade','x'),
("Fairy's Trinket",'x'),
('Falcon Blade','x'),
('Fallen Sky','x'),
('Flicker','x'),
('Fluffy Hat','x'),
('Force Boots','x'),
('Force Staff','x'),
('Gauntlets of Strength','x'),
('Gem of True Sight','x'),
('Ghost Scepter','x'),
("Giant's Ring",'x'),
('Glepnir','x'),
('Glimmer Cape','x'),
('Gloves of Haste','x'),
('Grove Bow','x'),
('Guardian Greaves','x'),
('Hand of Midas','x'),
('Headdress','x'),
('Heart of Tarrasque','x'),
("Heaven's Halberd",'x'),
('Helm of Iron Will','x'),
('Helm of the Dominator','x'),
('Helm of the Overlord','x'),
('Holy Locket','x'),
('Hood of Defiance','x'),
('Hurricane Pike','x'),
('Hyperstone','x'),
('Infused Raindrops','x'),
('Iron Branch','x'),
('Javelin','x'),
('Kaya','x'),
('Kaya and Sange','x'),
('Keen Optic','x'),
("Linken's Sphere",'x'),
('Lotus Orb','x'),
('Maelstrom','x'),
('Mage Slayer','x'),
('Magic Stick','x'),
('Magic Wand','x'),
('Manta Style','x'),
('Mantle of Intelligence','x'),
('Mask of Madness','x'),
('Medallion of Courage','x'),
('Mekansm','x'),
('Meteor Hammer','x'),
('Mind Breaker','x'),
('Mirror Shield','x'),
('Mithril Hammer','x'),
('Mjollnir','x'),
('Monkey King Bar','x'),
('Moon Shard','x'),
('Morbid Mask','x'),
('Mystic Staff','x'),
('Nether Shawl','x'),
('Ninja Gear','x'),
('Null Talisman','x'),
('Nullifier','x'),
('Oblivion Staff','x'),
('Observer Ward','x'),
('Ocean Heart','x'),
('Octarine Core','x'),
('Ogre Axe','x'),
('Orb of Corrosion','x'),
('Orb of Venom','x'),
('Orchid Malevolence','x'),
('Overwhelming Blink','x'),
('Paladin Sword','x'),
('Penta-Edged Sword','x'),
('Perseverance','x'),
('Phase Boots','x'),
("Philosopher's Stone",'x'),
('Pig Pole','x'),
('Pipe of Insight','x'),
('Pirate Hat','x'),
('Platemail','x'),
('Point Booster','x'),
('Possessed Mask','x'),
('Power Treads','x'),
('Psychic Headband','x'),
("Pupil's Gift",'x'),
('Quarterstaff','x'),
('Quelling Blade','x'),
('Quickening Charm','x'),
('Quicksilver Amulet','x'),
('Radiance','x'),
('Reaver','x'),
('Refresher Orb','x'),
('Refresher Shard','x'),
("Revenant's Brooch",'x'),
('Ring of Aquila','x'),
('Ring of Basilius','x'),
('Ring of Health','x'),
('Ring of Protection','x'),
('Ring of Regen','x'),
('Robe of the Magi','x'),
('Rod of Atos','x'),
('Sacred Relic','x'),
("Sage's Mask",'x'),
('Sange','x'),
('Sange and Yasha','x'),
('Satanic','x'),
('Scythe of Vyse','x'),
('Seer Stone','x'),
('Sentry Ward','x'),
('Shadow Amulet','x'),
('Shadow Blade','x'),
("Shiva's Guard",'x'),
('Silver Edge','x'),
('Skull Basher','x'),
('Slippers of Agility','x'),
('Smoke of Deceit','x'),
('Solar Crest','x'),
('Soul Booster','x'),
('Soul Ring','x'),
('Spell Prism','x'),
('Spider Legs','x'),
('Spirit Vessel','x'),
('Staff of Wizardry','x'),
('Stormcaller','x'),
('Swift Blink','x'),
('Talisman of Evasion','x'),
('Tango','x'),
('Telescope','x'),
('The Leveller','x'),
('Timeless Relic','x'),
('Titan Silver','x'),
('Tome of Knowledge','x'),
('Town Portal Scroll','x'),
('Tranquil Boots','x'),
('Trickster Cloak','x'),
('Trusty Shovel','x'),
("Tumbler's Toy",'x'),
('Ultimate Orb','x'),
('Urn of Shadows','x'),
('Vambrace','x'),
('Vanguard','x'),
('Veil of Discord','x'),
('Vitality Booster','x'),
("Vladmir's Offering",'x'),
('Void Stone','x'),
('Voodoo Mask','x'),
('Wind Lace','x'),
('Wind Waker','x'),
('Witch Blade','x'),
('Witchbane','x'),
('Wraith Band','x'),
('Wraith Pact','x'),
('Yasha','x'),
('Yasha and Kaya','x');

-- INSERT ITEMS INTO DATABASE
INSERT INTO DotaBaseDB.Abilities (HeroID, AbilityName, AbilityIconLink)
VALUES
('1','Mist Coil','x'),
('1','Aphotic Shield','x'),
('1','Curse of Avernus','x'),
('1','Borrowed Time','x'),
('1','Curse of Avernus - Shard Ability Upgrade','x'),
('1','Borrowed Time - Scepter Ability Upgrade','x'),
('2','Acid Spray','x'),
('2','Unstable Concoction','x'),
('2',"Greevil's Greed",'x'),
('2','Chemical Rage','x'),
('2','Berserk Potion','x'),
('2','Chemical Rage - Scepter Ability Upgrade','x'),
('3','Cold Feet','x'),
('3','Ice Vortex','x'),
('3','Chilling Touch','x'),
('3','Ice Blast','x'),
('3','Ice Vortex - Shard Ability Upgrade','x'),
('3','Chilling Touch - Scepter Ability Upgrade','x'),
('4','Mana Break','x'),
('4','Blink','x'),
('4','Counterspell','x'),
('4','Mana Void','x'),
('4','Counterspell - Shard Ability Upgrade','x'),
('4','Blink Fragment','x'),
('5','Flux','x'),
('5','Magnetic Field','x'),
('5','Spark Wraith','x'),
('5','Tempest Double','x'),
('5','Magnetic Field - Shard Ability Upgrade','x'),
('5','Spark Wraith - Scepter Ability Upgrade','x'),
('6',"Berserker's Call",'x'),
('6','Battle Hunger','x'),
('6','Counter Helix','x'),
('6','Culling Blade','x'),
('6','Counter Helix - Shard Ability Upgrade','x'),
('6',"Berserker's Call - Scepter Ability Upgrade",'x'),
('7','Enfeeble','x'),
('7','Brain Sap','x'),
('7','Nightmare','x'),
('7',"Fiend's Grip",'x'),
('7','Brain Sap - Shard Ability Upgrade','x'),
('7',"Fiend's Grip - Scepter Ability Upgrade",'x'),
('8','Sticky Napalm','x'),
('8','Flamebreak','x'),
('8','Firefly','x'),
('8','Flaming Lasso','x'),
('8','Sticky Napalm - Shard Ability Upgrade','x'),
('8','Flaming Lasso - Scepter Ability Upgrade','x'),
('9','Wild Axes','x'),
('9','Call of the Wild Board','x'),
('9','Call of the Wild Hawk','x'),
('9','Inner Beast','x'),
('9','Primal Roar','x'),
('9','Call of the Wild Hawk - Shard Ability Upgrade','x'),
('9','Wild Axes - Scepter Ability Upgrade','x'),
('10','Bloodrage','x'),
('10','Bloodrite','x'),
('10','Thirst','x'),
('10','Rupture','x'),
('10','Bloodrage - Shard Ability Upgrade','x'),
('10','Blood Mist','x'),
('11','Shuriken Toss','x'),
('11','Jinada','x'),
('11','Shadow Walk','x'),
('11','Track','x'),
('11','Shadow Walk - Shard Ability Upgrade','x'),
('11','Shuriken Toss - Scepter Ability Upgrade','x'),
('12','Thunder Clap','x'),
('12','Cinder Brew','x'),
('12','Drunken Brawler','x'),
('12','Primal Split','x'),
('12','Primal Split - Shard Ability Upgrade','x'),
('12','Primal Split - Shard Ability Upgrade','x'),
('13','Viscous Nasal Goo','x'),
('13','Quill Spray','x'),
('13','Bristleback','x'),
('13','Warpath','x'),
('13','Hairball','x'),
('13','Viscous Nasal Goo - Scepter Ability Upgrade','x'),
('14','Insatiable Hunger','x'),
('14','Spin Web','x'),
('14','Silken Bola','x'),
('14','Spawn Spiderlings','x'),
('14','Silken Bola - Shard Ability Upgrade','x'),
('14',"Spinner's Snare",'x'),
('15','Hoof Stomp','x'),
('15','Double Edge','x'),
('15','Retaliate','x'),
('15','Stampede','x'),
('15','Double Edge - Shard Ability Upgrade','x'),
('15','Stampede - Scepter Ability Upgrade','x'),
('15','Chaos Bolt','x'),
('15','Reality Rift','x'),
('15','Chaos Strike','x'),
('15','Phantasm','x'),
('15','Chaos Bolt - Shard Ability Upgrade','x'),
('15','Phantasm - Scepter Ability Upgrade','x');#

INSERT INTO DotaBaseDB.Users (Username, UserPassword)
VALUES
('test', 'test');

INSERT INTO DotaBaseDB.CountersTo (HeroID, UserID, CounterUserInfo)
VALUES
('2', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('4', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.');


INSERT INTO DotaBaseDB.CounteredBy (HeroID, UserID, CounteredUserInfo)
VALUES
('6', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.');