DROP DATABASE IF EXISTS DotaBaseDB;

CREATE DATABASE DotaBaseDB;

CREATE TABLE DotaBaseDB.Users (
    UserID int(11) NOT NULL AUTO_INCREMENT,
    Username varchar(45),
    UserPassword varchar(90),
    EmailAddress varchar(40),
    PRIMARY KEY (UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Heroes (
    HeroID int(11) NOT NULL AUTO_INCREMENT,
    HeroName varchar(40),
    HeroIconLink varchar(255),
    HeroAttribute varchar(20),
    HeroRole varchar(15),
    HeroLane1 varchar(15),
    HeroLane2 varchar(15),
    PRIMARY KEY (HeroID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.Abilities (
    AbilityID int (11) NOT NULL AUTO_INCREMENT,
    HeroID int (11),
    AbilityName varchar(30),
    AbilityIconLink varchar(255),
    PRIMARY KEY (AbilityID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.AbilityInfo (
    AbilityInfoID int(11) NOT NULL AUTO_INCREMENT,
    AbilityID int(11),
    UserID int(11),
    AbilityUserInfo TEXT,
    AbilityUpVote int DEFAULT 0,
    AbilityDownVote int DEFAULT 0,
    AbilityTag varchar(255),
    PRIMARY KEY (AbilityInfoID),
    FOREIGN KEY (AbilityID) REFERENCES Abilities(AbilityID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.AbilityVote (
    UserID int(11),
    AbilityInfoID int(11),
    AbilityVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, AbilityInfoID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (AbilityInfoID) REFERENCES AbilityInfo(AbilityInfoID)
);

CREATE TABLE DotaBaseDB.CountersTo (
    CounterID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    CounterUserInfo TEXT,
    CounterTotalUpVote int DEFAULT 0,
    CounterTotalDownVote int DEFAULT 0,
    CounterToTotalVotes int AS (CounterTotalUpVote - CounterTotalDownVote),
    CounterTag varchar(255),
    PRIMARY KEY (CounterID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.CounterToVote (
    UserID int(11),
    CounterID int(11),
    CounterUpVote BOOLEAN NOT NULL,
    CounterDownVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, CounterID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (CounterID) REFERENCES CountersTo(CounterID)
);

CREATE TABLE DotaBaseDB.CounteredBy (
    CounteredID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    CounteredUserInfo TEXT,
    CounteredTotalUpVote int DEFAULT 0,
    CounteredTotalDownVote int DEFAULT 0,
    CounteredByTotalVotes int AS (CounteredTotalUpVote - CounteredTotalDownVote),
    CounteredTag varchar(255),
    PRIMARY KEY (CounteredID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.CounteredByVote (
    UserID int(11),
    CounteredID int(11),
    CounteredUpVote BOOLEAN NOT NULL,
    CounteredDownVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, CounteredID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (CounteredID) REFERENCES CounteredBy(CounteredID)
);

CREATE TABLE DotaBaseDB.Items (
    ItemID int(11) NOT NULL AUTO_INCREMENT,
    ItemName varchar(30),
    ItemIconLink varchar(255),
    PRIMARY KEY (ItemID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.ItemInfo (
    ItemInfoID int(11) NOT NULL AUTO_INCREMENT,
    ItemID int(11),
    UserID int(11),
    ItemUserInfo TEXT,
    ItemTotalUpVote int DEFAULT 0,
    ItemTotalDownVote int DEFAULT 0,
    ItemTotalVotes int AS (ItemTotalUpVote - ItemTotalDownVote),
    ItemInfoTag varchar(255),
    PRIMARY KEY (ItemInfoID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.ItemInfoVote (
    UserID int(11),
    ItemInfoID int(11),
    ItemUpVote BOOLEAN NOT NULL,
    ItemDownVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, ItemInfoID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (ItemInfoID) REFERENCES ItemInfo(ItemInfoID)
);

CREATE TABLE DotaBaseDB.HeroItemsFor (
    HeroItemForID int(11) NOT NULL AUTO_INCREMENT,
    ItemID int(11),
    UserID int(11),
    HeroItemForUserInfo TEXT,
    HeroItemForTotalUpVote int DEFAULT 0,
    HeroItemForTotalDownVote int DEFAULT 0,
    HeroItemForTotalVotes int AS (HeroItemForTotalUpVote - HeroItemForTotalDownVote),
    ItemForTag varchar(255),
    PRIMARY KEY (HeroItemForID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.HeroItemsForVote (
    UserID int(11),
    HeroItemForID int(11),
    HeroItemForUpVote BOOLEAN NOT NULL,
    HeroItemForDownVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, HeroItemForID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (HeroItemForID) REFERENCES HeroItemsFor(HeroItemForID)
);

CREATE TABLE DotaBaseDB.HeroItemsAgainst (
    HeroItemAgainstID int(11) NOT NULL AUTO_INCREMENT,
    ItemID int(11),
    UserID int(11),
    HeroItemAgainstUserInfo TEXT,
    HeroItemAgainstTotalUpVote int DEFAULT 0,
    HeroItemAgainstTotalDownVote int DEFAULT 0,
    HeroItemAgainstTotalVotes int AS (HeroItemAgainstTotalUpVote - HeroItemAgainstTotalDownVote),
    ItemAgainstTag varchar(255),
    PRIMARY KEY (HeroItemAgainstID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

CREATE TABLE DotaBaseDB.HeroItemsAgainstVote (
    UserID int(11),
    HeroItemAgainstID int(11),
    HeroItemAgainstUpVote BOOLEAN NOT NULL,
    HeroItemAgainstDownVote BOOLEAN NOT NULL,
    PRIMARY KEY (UserID, HeroItemAgainstID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (HeroItemAgainstID) REFERENCES HeroItemsAgainst(HeroItemAgainstID)
);

CREATE TABLE DotaBaseDB.Disscussion (
    LogID int(11) NOT NULL AUTO_INCREMENT,
    HeroID int(11),
    UserID int(11),
    LogText TEXT,
    Upvote int(11),
    DownVote int(11),
    PRIMARY KEY (LogID),
    FOREIGN KEY (HeroID) REFERENCES Heroes(HeroID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)AUTO_INCREMENT=1;

-- INSERT HEROES INTO DATABASE
INSERT INTO DotaBaseDB.Heroes (HeroName, HeroIconLink, HeroAttribute, HeroRole, HeroLane1, HeroLane2)
VALUES
('abaddon','images/heroes/abaddon/abaddon.png','Strength','Core','Off Lane','Safe Lane'),
('alchemist','images/heroes/alchemist/alchemist.png','Strength','Core','Mid Lane','Safe Lane'),
('ancient-apparition','images/heroes/ancient_apparition/ancient_apparition.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('anti-mage','images/heroes/anti-mage/antimage.png','Agility','Core','Safe Lane', ''),
('arc-warden','images/heroes/arc_warden/arc_warden.png','Agility','Core','Mid Lane', 'Safe Lane'),
('axe','images/heroes/axe/axe.png','Strength','Core','Off Lane', ''),
('bane','images/heroes/bane/bane.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('batrider','images/heroes/batrider/batrider.png','Intelligence','Support','Safe Lane', 'Mid Lane'),
('beastmaster','images/heroes/beastmaster/beastmaster.png','Strength','Core','Off Lane', ''),
('bloodseeker','images/heroes/bloodseeker/bloodseeker.png','Agility','Core','Safe Lane', 'Off Lane'),
('bounty-hunter','images/heroes/bounty_hunter/bounty_hunter.png','Agility','Core','Off Lane', ''),
('brewmaster','images/heroes/brewmaster/brewmaster.png','Strength','Core','Off Lane', 'Mid Lane'),
('bristleback','images/heroes/bristleback/bristleback.png','Strength','Core','Off Lane', ''),
('broodmother','images/heroes/broodmother/broodmother.png','Agility','Core','Mid Lane', 'Off Lane'),
('centaur-warrunner','images/heroes/centaur_warrunner/centaur.png','Strength','Core','Off Lane', ''),
('chaos-knight','images/heroes/chaos_knight/chaos_knight.png','Strength','Core','Safe Lane', 'Off Lane'),
('chen','images/heroes/chen/chen.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('clinkz','images/heroes/clinkz/clinkz.png','Agility','Core','Safe Lane', 'Mid Lane'),
('clockwerk','images/heroes/clockwerk/clockwerk.png','Strength','Core','Off Lane', 'Safe Lane'),
('crystal-maiden','images/heroes/crystal_maiden/crystal_maiden.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('dark-seer','images/heroes/dark_seer/dark_seer.png','Intelligence','Support','Off Lane', ''),
('dark-willow','images/heroes/dark_willow/dark_willow.png','Intelligence','Support','Off Lane', 'Safe Lane'),
('dawnbreaker','images/heroes/dawnbreaker/dawnbreaker.png','Strength','Support','Off Lane', ''),
('dazzle','images/heroes/dazzle/dazzle.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('death-prophet','images/heroes/death_prophet/death_prophet.png','Intelligence','Core','Mid Lane', 'Off Lane'),
('disruptor','images/heroes/disruptor/disruptor.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('doom','images/heroes/doom/doom.png','Strength','Core','Off Lane', ''),
('dragon-knight','images/heroes/dragon_knight/dragon_knight.png','Strength','Core','Off Lane', 'Mid Lane'),
('drow-ranger','images/heroes/drow_ranger/drow_ranger.png','Agility','Core','Safe Lane', 'Mid Lane'),
('earth-spirit','images/heroes/earth_spirit/earth_spirit.png','Strength','Support','Off Lane', 'Safe Lane'),
('earthshaker','images/heroes/earthshaker/earthshaker.png','Strength','Support','Off Lane', 'Safe Lane'),
('elder-titan','images/heroes/elder_titan/elder_titan.png','Strength','Support','Off Lane', 'Safe Lane'),
('ember-spirit','images/heroes/ember_spirit/ember_spirit.png','Agility','Core','Mid Lane', 'Safe Lane'),
('enchantress','images/heroes/enchantress/enchantress.png','Intelligence','Support','Off Lane', 'Safe Lane'),
('enigma','images/heroes/enigma/enigma.png','Intelligence','Core','Off Lane', ''),
('faceless-void','images/heroes/faceless_void/faceless_void.png','Agility','Core','Safe Lane', 'Off Lane'),
('grimstroke','images/heroes/grimstroke/grimstroke.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('gyrocopter','images/heroes/gyrocopter/gyrocopter.png','Agility','Core','Safe Lane', 'Off Lane'),
('hoodwink','images/heroes/hoodwink/hoodwink.png','Agility','Support','Off Lane', 'Safe Lane'),
('huskar','images/heroes/huskar/huskar.png','Strength','Core','Mid Lane', 'Safe Lane'),
('invoker','images/heroes/invoker/invoker.png','Intelligence','Core','Mid Lane', ''),
('io','images/heroes/io/io.png','Strength','Support','Safe Lane', 'Off Lane'),
('jakiro','images/heroes/jakiro/jakiro.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('juggernaut','images/heroes/juggernaut/juggernaut.png','Agility','Core','Safe Lane', ''),
('keeper-of-the-light','images/heroes/keeper_of_the_light/keeper_of_the_light.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('kunkka','images/heroes/kunkka/kunkka.png','Strength','Core','Mid Lane', 'Safe Lane'),
('legion-commander','images/heroes/legion_commander/legion_commander.png','Strength','Core','Off Lane', 'Safe Lane'),
('leshrac','images/heroes/leshrac/leshrac.png','Intelligence','Core','Mid Lane', 'Off Lane'),
('lich','images/heroes/lich/lich.png','images/heroes/lich.png','Support','Safe Lane', 'Off Lane'),
('lifestealer','images/heroes/lifestealer/life_stealer.png','Strength','Core','Safe Lane', ''),
('lina','images/heroes/lina/lina.png','Intelligence','Core','Mid Lane', 'Off Lane'),
('lion','images/heroes/lion/lion.png','Intelligence','Support','Safe Lane', 'Off Lane'),
('lone-druid','images/heroes/lone_druid/lone_druid.png','Agility','Core','Off Lane', 'Safe Lane'),
('luna','images/heroes/luna/luna.png','Agility','Core','Safe Lane', 'Off Lane'),
('lycan','images/heroes/lycan/lycan.png','Strength','Core','Safe Lane', 'Off Lane'),
('magnus','images/heroes/magnus/magnus.png','Strength','Support','Off Lane', 'Mid Lane'),
('marci','images/heroes/marci/marci.png','Strength','Core','Off Lane', 'Safe Lane'),
('mars','images/heroes/mars/mars.png','Strength','Core','Off Lane', ''),
('medusa','images/heroes/medusa/medusa.png','Agility','Core','Safe Lane', 'Mid Lane'),
('meepo','images/heroes/meepo/meepo.png','Agility','Core','Mid Lane', ''),
('mirana','images/heroes/mirana/mirana.png','Agility','Support','Off Lane', 'Mid Lane'),
('monkey-king','images/heroes/monkey_king/monkey_king.png','Agility','Core','Safe Lane', 'Mid Lane'),
('morphling','images/heroes/morphling/morphling.png','Agility','Core','Safe Lane', 'Mid Lane'),
('naga-siren','images/heroes/naga_siren/naga_siren.png','Agility','Core','Safe Lane', ''),
("nature's-prophet",'images/heroes/natures_prophet/natures_prophet.png','Intelligence','Core','Off Lane', ''),
('necrophos','images/heroes/necrophos/necrophos.png','Intelligence','Core','Off Lane', 'Mid Lane'),
('night-stalker','images/heroes/night_stalker/night_stalker.png','Strength','Core','Off Lane', ''),
('nyx-assassin','images/heroes/nyx_assassin/nyx_assassin.png','Agility','Support','Off Lane', 'Safe Lane'),
('ogre-magi','images/heroes/ogre_magi/ogre_magi.png','Strength','Support','Safe Lane', 'Off Lane'),
('omniknight','images/heroes/omniknight/omniknight.png','Strength','Support','Safe Lane', 'Off Lane'),
('oracle','images/heroes/oracle/oracle.png','Intelligence','Support','Safe Lane', ''),
('outworld-destroyer','images/heroes/outworld_destroyer/outworld_destroyer.png','Intelligence','Core','Mid Lane', ''),
('pangolier','images/heroes/pangolier/pangolier.png','Agility','Core','Off Lane', ''),
('phantom-assassin','images/heroes/phantom_assassin/phantom_assassin.png','Agility','Core','Safe Lane','Mid Lane'),
('phantom-lancer','images/heroes/phantom_lancer/phantom_lancer.png','Agility','Core','Safe Lane', ''),
('phoenix','images/heroes/phoenix/phoenix.png','Strength','Support','Off Lane','Safe Lane'),
('primal-beast','images/heroes/primal_beast/primal_beast.png','Strength','Support','Off Lane','Safe Lane'),
('puck','images/heroes/puck/puck.png','Intelligence','Core','Mid Lane','Off Lane'),
('pudge','images/heroes/pudge/pudge.png','Strength','Core','Off Lane','Mid Lane'),
('pugna','images/heroes/pugna/pugna.png','Intelligence','Support','Off Lane','Mid Lane'),
('queen-of-pain','images/heroes/queen_of_pain/queenofpain.png','Intelligence','Core','Mid Lane',''),
('razor','images/heroes/razor/razor.png','Agility','Core','Mid Lane','Off Lane'),
('riki','images/heroes/riki/riki.png','Agility','Core','Off Lane','Safe Lane'),
('rubick','images/heroes/rubick/rubick.png','Intelligence','Support','Safe Lane','Off Lane'),
('sand-king','images/heroes/sand_king/sand_king.png','Strength','Core','Off Lane',''),
('shadow-demon','images/heroes/shadow_demon/shadow_demon.png','Intelligence','Support','Safe Lane','Off Lane'),
('shadow-fiend','images/heroes/shadow_fiend/shadow_fiend.png','Agility','Core','Mid Lane',''),
('shadow-shaman','images/heroes/shadow_shaman/shadow_shaman.png','Intelligence','Support','Safe Lane','Off Lane'),
('silencer','images/heroes/silencer/silencer.png','Intelligence','Support','Safe Lane','Off Lane'),
('skywrath-mage','images/heroes/skywrath_mage/skywrath_mage.png','Intelligence','Support','Off Lane','Safe Lane'),
('slardar','images/heroes/slardar/slardar.png','Strength','Core','Off Lane','Safe Lane'),
('slark','images/heroes/slark/slark.png','Agility','Core','Safe Lane',''),
('snapfire','images/heroes/snapfire/snapfire.png','Strength','Support','Off Lane','Safe Lane'),
('sniper','images/heroes/sniper/sniper.png','Agility','Core','Mid Lane','Safe Lane'),
('spectre','images/heroes/spectre/spectre.png','Agility','Core','Safe Lane',''),
('spirit-breaker','images/heroes/spirit_breaker/spirit_breaker.png','Strength','Core','Off Lane',''),
('storm-spirit','images/heroes/storm_spirit/storm_spirit.png','Intelligence','Core','Mid Lane',''),
('sven','images/heroes/sven/sven.png','Strength','Core','Safe Lane',''),
('techies','images/heroes/techies/techies.png','Intelligence','Support','Off Lane',''),
('templar-assassin','images/heroes/templar_assassin/templar_assassin.png','Agility','Core','Mid Lane',''),
('terrorblade','images/heroes/terrorblade/terrorblade.png','Agility','Core','Safe Lane',''),
('tidehunter','images/heroes/tidehunter/tidehunter.png','Strength','Core','Off Lane',''),
('timbersaw','images/heroes/timbersaw/timbersaw.png','Strength','Core','Off Lane',''),
('tinker','images/heroes/tinker/tinker.png','Intelligence','Core','Mid Lane',''),
('tiny','images/heroes/tiny/tiny.png','Strength','Core','Off Lane','Mid Lane'),
('treant-protector','images/heroes/treant_protector/treant.png','Strength','Support','Safe Lane','Off Lane'),
('troll-warlord','images/heroes/troll_warlord/troll_warlord.png','Agility','Core','Safe Lane',''),
('tusk','images/heroes/tusk/tusk.png','Strength','Core','Off Lane','Safe Lane'),
('underlord','images/heroes/underlord/underlord.png','Strength','Core','Off Lane',''),
('undying','images/heroes/undying/undying.png','Strength','Support','Off Lane','Safe Lane'),
('ursa','images/heroes/ursa/ursa.png','Agility','Core','Safe Lane',''),
('vengeful-spirit','images/heroes/vengeful_spirit/vengefulspirit.png','Agility','Support','Safe Lane','Off Lane'),
('venomancer','images/heroes/venomancer/venomancer.png','Agility','Support','Off Lane','Safe Lane'),
('viper','images/heroes/viper/viper.png','Agility','Core','Mid Lane','Off Lane'),
('visage','images/heroes/visage/visage.png','Intelligence','Core','Mid Lane','Safe Lane'),
('void-spirit','images/heroes/void_spirit/void_spirit.png','Intelligence','Core','Mid Lane','Off Lane'),
('warlock','images/heroes/warlock/warlock.png','Intelligence','Support','Safe Lane','Off Lane'),
('weaver','images/heroes/weaver/weaver.png','Agility','Core','Off Lane','Safe Lane'),
('windranger','images/heroes/windranger/windranger.png','Intelligence','Core','Off Lane','Mid Lane'),
('winter-wyvern','images/heroes/winter_wyvern/winter_wyvern.png','Intelligence','Support','Safe Lane','Off Lane'),
('witch-doctor','images/heroes/witch_doctor/witch_doctor.png','Intelligence','Support','Safe Lane','Off Lane'),
('wraith-king','images/heroes/wraith_king/wraith_king.png','Strength','Core','Safe Lane','Off Lane'),
('zeus','images/heroes/zeus/zeus.png','Intelligence','Core','Mid Lane','Off Lane');

-- INSERT ITEMS INTO DATABASE
INSERT INTO DotaBaseDB.Items (ItemName, ItemIconLink)
VALUES
('abyssal-blade','images/items/abyssal_blade.png'),
('aegis-of-the-immortal','images/items/aegis_of_the_immortal.png'),
('aeon-disk','images/items/aeon_disk.png'),
('aether-lens','images/items/aether_lens.png'),
("aghanim's-scepter",'images/items/aghanims_scepter.png'),
("aghanim's-blessing",'images/items/aghanims_blessing.png'),
("aghanim's-blessing-roshan",'images/items/aghanims_blessing-roshan.png'),
("aghanim's-shard",'images/items/aghanims_shard.png'),
('apex','images/items/apex.png'),
('arcane-blink','images/items/arcane_blink.png'),
('arcane-boots','images/items/arcane_boots.png'),
('arcane-ring','images/items/arcane_ring.png'),
("arcanist's-armor",'images/items/arcanists_armor.png'),
('armlet-of-mordiggian','images/items/armlet_of_mordiggian.png'),
("ascetic-cap",'images/items/ascetic_cap.png'),
('assault-cuirass','images/items/assault_cuirass.png'),
('band-of-elvenskin','images/items/band_of_elvenskin.png'),
('battle-fury','images/items/battle_fury.png'),
('belt-of-strength','images/items/belt_of_strength.png'),
('black-king-bar','images/items/black_king_bar.png'),
('blade-mail','images/items/blade_mail.png'),
('blade-of-alacrity','images/items/blade_of_alacrity.png'),
('blades-of-attack','images/items/blades_of_attack.png'),
('blast-rig','images/items/blast_rig.png'),
('blight-stone','images/items/blight_stone.png'),
('blink-dagger','images/items/blink_dagger.png'),
('blitz-knuckles','images/items/blitz_knuckles.png'),
('bloodstone','images/items/bloodstone.png'),
('bloodthorn','images/items/bloodthorn.png'),
('book-of-shadows','images/items/book_of_shadows.png'),
('book-of-the-dead','images/items/book_of_the_dead.png'),
('boots-of-bearing','images/items/boots_of_bearing.png'),
('boots-of-speed','images/items/boots_of_speed.png'),
('boots-of-travel','images/items/boots_of_travel.png'),
('boots-of-travel-2','images/items/boots_of_travel_2.png'),
('bottle','images/items/bottle.png'),
('bracer','images/items/bracer.png'),
("brigand's-blade",'images/items/brigands_blade.png'),
('broadsword','images/items/broadsword.png'),
('broom-handle','images/items/broom_handle.png'),
('buckler','images/items/buckler.png'),
('bullwhip','images/items/bullwhip.png'),
('butterfly','images/items/butterfly.png'),
('ceremonial-robe','images/items/ceremonial_robe.png'),
('chainmail','images/items/chainmail.png'),
('cheese','images/items/cheese.png'),
('chipped-vest','images/items/chipped_vest.png'),
('circlet','images/items/circlet.png'),
('clarity','images/items/clarity.png'),
('claymore','images/items/claymore.png'),
('cloak','images/items/cloak.png'),
('cloak-of-flames','images/items/cloak_of_flames.png'),
('crimson-guard','images/items/crimson_guard.png'),
('crown','images/items/crown.png'),
('crystalys','images/items/crystalys.png'),
('daedalus','images/items/daedalus.png'),
('dagon','images/items/dagon.png'),
('dagon-level-2','images/items/dagon_level_2.png'),
('dagon-level-3','images/items/dagon_level_3.png'),
('dagon-level-4','images/items/dagon_level_4.png'),
('dagon-level-5','images/items/dagon_level_5.png'),
('demon-edge','images/items/demon_edge.png'),
('desolator','images/items/desolator.png'),
('diffusal-blade','images/items/diffusal_blade.png'),
('divine-rapier','images/items/divine_rapier.png'),
('dragon-lance','images/items/dragon_lance.png'),
('dragon-scale','images/items/dragon_scale.png'),
('drum-of-endurance','images/items/drum_of_endurance.png'),
('dust-of-appearance','images/items/dust_of_appearance.png'),
('eaglesong','images/items/eaglesong.png'),
('echo-sabre','images/items/echo_sabre.png'),
('elven-tunic','images/items/elven_tunic.png'),
('enchanted-mango','images/items/enchanted_mango.png'),
('enchanted-quiver','images/items/enchanted_quiver.png'),
('energy-booster','images/items/energy_booster.png'),
('essence-ring','images/items/essence_ring.png'),
('eternal-shroud','images/items/eternal_shroud.png'),
('ethereal-blade','images/items/ethereal_blade.png'),
("eul's-scepter-of-divinity",'images/items/euls_scepter_of_divinity.png'),
('ex-machina','images/items/ex_machina.png'),
('eye-of-skadi','images/items/eye_of_skadi.png'),
('fae-grenade','images/items/fae_grenade.png'),
('faerie-fire','images/items/faerie_fire.png'),
("fairy's-trinket",'images/items/fairys_trinket.png'),
('falcon-blade','images/items/falcon_blade.png'),
('fallen-sky','images/items/fallen_sky.png'),
('flicker','images/items/flicker.png'),
('fluffy-hat','images/items/fluffy_hat.png'),
('force-boots','images/items/force_boots.png'),
('force-staff','images/items/force_staff.png'),
('gauntlets-of-strength','images/items/gauntlets_of_strength.png'),
('gem-of-true-sight','images/items/gem_of_true_sight.png'),
('ghost-scepter','images/items/ghost_scepter.png'),
("giant's-ring",'images/items/giants_ring.png'),
('gleipnir','images/items/gleipnir.png'),
('glimmer-cape','images/items/glimmer_cape.png'),
('gloves-of-haste','images/items/gloves_of_haste.png'),
('grove-bow','images/items/grove_bow.png'),
('guardian-greaves','images/items/guardian_greaves.png'),
('hand-of-midas','images/items/hand_of_midas.png'),
('headdress','images/items/headdress.png'),
('heart-of-tarrasque','images/items/heart_of_tarrasque.png'),
('healing-salve','images/items/healing_salve.png'),
("heaven's-halberd",'images/items/heavens_halberd.png'),
('helm-of-iron-will','images/items/helm_of_iron_will.png'),
('helm-of-the-dominator','images/items/helm_of_the_dominator.png'),
('helm-of-the-overlord','images/items/helm_of_the_overlord.png'),
('holy-locket','images/items/holy_locket.png'),
('hood-of-defiance','images/items/hood_of_defiance.png'),
('hurricane-pike','images/items/hurricane_pike.png'),
('hyperstone','images/items/hyperstone.png'),
('infused-raindrops','images/items/infused_raindrop.png'),
('iron-branch','images/items/iron_branch.png'),
('javelin','images/items/javelin.png'),
('kaya','images/items/kaya.png'),
('kaya-and-sange','images/items/kaya_and_sange.png'),
('keen-optic','images/items/keen_optic.png'),
("linken's-sphere",'images/items/linkens_sphere.png'),
('lotus-orb','images/items/lotus_orb.png'),
('maelstrom','images/items/maelstrom.png'),
('mage-slayer','images/items/mage_slayer.png'),
('magic-stick','images/items/magic_stick.png'),
('magic-wand','images/items/magic_wand.png'),
('manta-style','images/items/manta_style.png'),
('mantle-of-intelligence','images/items/mantle_of_intelligence.png'),
('mask-of-madness','images/items/mask_of_madness.png'),
('medallion-of-courage','images/items/medallion_of_courage.png'),
('mekansm','images/items/mekansm.png'),
('meteor-hammer','images/items/meteor_hammer.png'),
('mind-breaker','images/items/mind_breaker.png'),
('mirror-shield','images/items/mirror_shield.png'),
('mithril-hammer','images/items/mithril_hammer.png'),
('mjollnir','images/items/mjollnir.png'),
('monkey-king-bar','images/items/monkey_king_bar.png'),
('moon-shard','images/items/moon_shard.png'),
('morbid-mask','images/items/morbid_mask.png'),
('mystic-staff','images/items/mystic_staff.png'),
('nether-shawl','images/items/nether_shawl.png'),
('ninja-gear','images/items/ninja_gear.png'),
('null-talisman','images/items/null_talisman.png'),
('nullifier','images/items/nullifier.png'),
('oblivion-staff','images/items/oblivion_staff.png'),
('observer-ward','images/items/observer_ward.png'),
('observer-and-sentry-wards','images/items/observer_and_sentry_wards.png'),
('ocean-heart','images/items/ocean_heart.png'),
('octarine-core','images/items/octarine_core.png'),
('ogre-axe','images/items/ogre_axe.png'),
('orb-of-corrosion','images/items/orb_of_corrosion.png'),
('orb-of-venom','images/items/orb_of_venom.png'),
('orchid-malevolence','images/items/orchid_malevolence.png'),
('overwhelming-blink','images/items/overwhelming_blink.png'),
('paladin-sword','images/items/paladin_sword.png'),
('penta-edged-sword','images/items/penta_edged_sword.png'),
('perseverance','images/items/perseverance.png'),
('phase-boots','images/items/phase_boots.png'),
("philosopher's-stone",'images/items/philosophers_stone.png'),
('pig-pole','images/items/pig_pole.png'),
('pipe-of-insight','images/items/pipe_of_insight.png'),
('pirate-hat','images/items/pirate_hat.png'),
('platemail','images/items/platemail.png'),
('point-booster','images/items/point_booster.png'),
('possessed-mask','images/items/possessed_mask.png'),
('power-treads','images/items/power_treads.png'),
('psychic-headband','images/items/psychic_headband.png'),
("pupil's-gift",'images/items/pupils_gift.png'),
('quarterstaff','images/items/quarterstaff.png'),
('quelling-blade','images/items/quelling_blade.png'),
('quickening-charm','images/items/quickening_charm.png'),
('quicksilver-amulet','images/items/quicksilver_amulet.png'),
('radiance','images/items/radiance.png'),
('reaver','images/items/reaver.png'),
('refresher-orb','images/items/refresher_orb.png'),
('refresher-shard','images/items/refresher_shard.png'),
("revenants-brooch",'images/items/revenants_brooch.png'),
('ring-of-aquila','images/items/ring_of_aquila.png'),
('ring-of-basilius','images/items/ring_of_basilius.png'),
('ring-of-health','images/items/ring_of_health.png'),
('ring-of-protection','images/items/ring_of_protection.png'),
('ring-of-regen','images/items/ring_of_regen.png'),
('robe-of-the-magi','images/items/robe_of_the_magi.png'),
('rod-of-atos','images/items/rod_of_atos.png'),
('sacred-relic','images/items/sacred_relic.png'),
("sage's-mask",'images/items/sages_mask.png'),
('sange','images/items/sange.png'),
('sange-and-yasha','images/items/sange_and_yasha.png'),
('satanic','images/items/satanic.png'),
('scythe-of-vyse','images/items/scythe_of_vyse.png'),
('seer-stone','images/items/seer_stone.png'),
('sentry-ward','images/items/sentry_ward.png'),
('shadow-amulet','images/items/shadow_amulet.png'),
('shadow-blade','images/items/shadow_blade.png'),
("shiva's-guard",'images/items/shivas_guard.png'),
('silver-edge','images/items/silver_edge.png'),
('skull-basher','images/items/skull_basher.png'),
('slippers-of-agility','images/items/slippers_of_agility.png'),
('smoke-of-deceit','images/items/smoke_of_deceit.png'),
('solar-crest','images/items/solar_crest.png'),
('soul-booster','images/items/soul_booster.png'),
('soul-ring','images/items/soul_ring.png'),
('spell-prism','images/items/spell_prism.png'),
('spider-legs','images/items/spider_legs.png'),
('spirit-vessel','images/items/spirit_vessel.png'),
('staff-of-wizardry','images/items/staff_of_wizardry.png'),
('stormcrafter','images/items/stormcrafter.png'),
('stygian-desolator','images/items/stygian_desolator.png'),
('swift-blink','images/items/swift_blink.png'),
('talisman-of-evasion','images/items/talisman_of_evasion.png'),
('tango','images/items/tango.png'),
('telescope','images/items/telescope.png'),
('the-leveller','images/items/the_leveller.png'),
('timeless-relic','images/items/timeless_relic.png'),
('titan-sliver','images/items/titan_sliver.png'),
('tome-of-knowledge','images/items/tome_of_knowledge.png'),
('town-portal-scroll','images/items/town_portal_scroll.png'),
('tranquil-boots','images/items/tranquil_boots.png'),
('trickster-cloak','images/items/trickster_cloak.png'),
('trusty-shovel','images/items/trusty_shovel.png'),
("tumbler's-toy",'images/items/tumblers_toy.png'),
('ultimate-orb','images/items/ultimate_orb.png'),
('urn-of-shadows','images/items/urn_of_shadows.png'),
('vambrace','images/items/vambrace.png'),
('vanguard','images/items/vanguard.png'),
('veil-of-discord','images/items/veil_of_discord.png'),
('vitality-booster','images/items/vitality_booster.png'),
("vladmir's-offering",'images/items/vladmirs_offering.png'),
('void-stone','images/items/void_stone.png'),
('voodoo-mask','images/items/voodoo_mask.png'),
('wind-lace','images/items/wind_lace.png'),
('wind-waker','images/items/wind_waker.png'),
('witch-blade','images/items/witch_blade.png'),
('witchbane','images/items/witchbane.png'),
('wraith-band','images/items/wraith_band.png'),
('wraith-pact','images/items/wraith_pact.png'),
('yasha','images/items/yasha.png'),
('yasha-and-kaya','images/items/yasha_and_kaya.png');

-- INSERT ITEMS INTO DATABASE
INSERT INTO DotaBaseDB.Abilities (HeroID, AbilityName, AbilityIconLink)
VALUES
('1','mist-coil','images/heroes/abaddon/abaddon_death_coil.png'),
('1','aphotic-shield','images/heroes/abaddon/abaddon_aphotic_shield.png'),
('1','curse-of-avernus','images/heroes/abaddon/abaddon_curse_of_avernus.png'),
('1','borrowed-time','images/heroes/abaddon/abaddon_borrowed_time.png'),
('1','curse-of-avernus-shard-ability-upgrade','images/heroes/abaddon/abaddon_curse_of_avernus-shard.png'),
('1','borrowed-time-scepter-ability-upgrade','images/heroes/abaddon/abaddon_borrowed_time-scepter.png'),
('2','acid-spray','images/heroes/alchemist/alchemist_acid_spray.png'),
('2','unstable-concoction','images/heroes/alchemist/alchemist_unstable_concoction.png'),
('2',"greevil's-greed",'images/heroes/alchemist/alchemist_goblins_greed.png'),
('2','chemical-rage','images/heroes/alchemist/alchemist_chemical_rage.png'),
('2','berserk-potion','images/heroes/alchemist/alchemist_berserk_potion-shard.png'),
('2','chemical-rage-scepter-ability-upgrade','images/heroes/alchemist/alchemist_chemical_rage-scepter.png'),
('3','cold-feet','images/heroes/ancient_apparition/ancient_apparition_cold_feet.png'),
('3','ice-vortex','images/heroes/ancient_apparition/ancient_apparition_ice_vortex.png'),
('3','chilling-touch','images/heroes/ancient_apparition/ancient_apparition_chilling_touch.png'),
('3','ice-blast','images/heroes/ancient_apparition/ancient_apparition_ice_blast.png'),
('3','ice-vortex-shard-ability-upgrade','images/heroes/ancient_apparition/ancient_apparition_ice_vortex-shard.png'),
('3','chilling-touch-scepter-ability-upgrade','images/heroes/ancient_apparition/ancient_apparition_chilling_touch-scepter.png'),
('4','mana-break','images/heroes/anti-mage/antimage_mana_break.png'),
('4','blink','images/heroes/anti-mage/antimage_blink.png'),
('4','counterspell','images/heroes/anti-mage/antimage_counterspell.png'),
('4','mana-void','images/heroes/anti-mage/antimage_mana_void.png'),
('4','counterspell-shard-ability-upgrade','images/heroes/anti-mage/antimage_counterspell-shard.png'),
('4','blink-fragment','images/heroes/anti-mage/antimage_mana_overload.png'),
('5','flux','images/heroes/arc_warden/arc_warden_flux.png'),
('5','magnetic-field','images/heroes/arc_warden/arc_warden_magnetic_field.png'),
('5','spark-wraith','images/heroes/arc_warden/arc_warden_spark_wraith.png'),
('5','tempest-double','images/heroes/arc_warden/arc_warden_tempest_double.png'),
('5','magnetic-field-shard-ability-upgrade','images/heroes/arc_warden/arc_warden_magnetic_field-shard.png'),
('5','spark-wraith-scepter-ability-upgrade','images/heroes/arc_warden/arc_warden_spark_wraith-scepter.png'),
('6',"berserker's-call",'images/heroes/axe/axe_berserkers_call.png'),
('6','battle-hunger','images/heroes/axe/axe_battle_hunger.png'),
('6','counter-helix','images/heroes/axe/axe_counter_helix.png'),
('6','culling-blade','images/heroes/axe/axe_culling_blade.png'),
('6','counter-helix-shard-ability-upgrade','images/heroes/axe/axe_counter_helix-shard.png'),
('6',"berserker's-call-scepter-ability-upgrade",'images/heroes/axe/axe_berserkers_call-scepter.png'),
('7','enfeeble','images/heroes/bane/bane_enfeeble.png'),
('7','brain-sap','images/heroes/bane/bane_brain_sap.png'),
('7','nightmare','images/heroes/bane/bane_nightmare.png'),
('7',"fiend's-grip",'images/heroes/bane/bane_fiends_grip.png'),
('7','brain-sap-shard-ability-upgrade','images/heroes/bane/bane_brain_sap-shard.png'),
('7',"fiend's-grip-Scepter-ability-upgrade",'images/heroes/bane/bane_fiends_grip-scepter.png'),
('8','sticky-napalm','images/heroes/batrider/batrider_sticky_napalm.png'),
('8','flamebreak','images/heroes/batrider/batrider_flamebreak.png'),
('8','firefly','images/heroes/batrider/batrider_firefly.png'),
('8','flaming-lasso','images/heroes/batrider/batrider_flaming_lasso.png'),
('8','sticky-napalm-shard-ability-upgrade','images/heroes/batrider/batrider_sticky_napalm-shard.png'),
('8','flaming-lasso-scepter-ability-upgrade','images/heroes/batrider/batrider_flaming_lasso-scepter.png'),
('9','wild-axes','images/heroes/beastmaster/beastmaster_wild_axes.png'),
('9','call-of-the-wild-boar','images/heroes/beastmaster/beastmaster_call_of_the_wild.png'),
('9','call-of-the-wild-hawk','images/heroes/beastmaster/beastmaster_call_of_the_wild_hawk.png'),
('9','inner-beast','images/heroes/beastmaster/beastmaster_inner_beast.png'),
('9','primal-roar','images/heroes/beastmaster/beastmaster_primal_roar.png'),
('9','call-of-the-wild-hawk-shard-ability-upgrade','images/heroes/beastmaster/beastmaster_call_of_the_wild_hawk-shard.png'),
('9','wild-axes-scepter-ability-upgrade','images/heroes/beastmaster/beastmaster_wild_axes-scepter.png'),
('10','bloodrage','images/heroes/bloodseeker/bloodseeker_bloodrage.png'),
('10','bloodrite','images/heroes/bloodseeker/bloodseeker_blood_bath.png'),
('10','thirst','images/heroes/bloodseeker/bloodseeker_thirst.png'),
('10','rupture','images/heroes/bloodseeker/bloodseeker_rupture.png'),
('10','bloodrage-shard-ability-upgrade','images/heroes/bloodseeker/bloodseeker_bloodrage-shard.png'),
('10','blood-mist','images/heroes/bloodseeker/bloodseeker_blood_mist.png'),
('11','shuriken-toss','images/heroes/bounty_hunter/bounty_hunter_shuriken_toss.png'),
('11','jinada','images/heroes/bounty_hunter/bounty_hunter_jinada.png'),
('11','shadow-walk','images/heroes/bounty_hunter/bounty_hunter_wind_walk.png'),
('11','track','images/heroes/bounty_hunter/bounty_hunter_track.png'),
('11','shadow-walk-shard-ability-upgrade','images/heroes/bounty_hunter/bounty_hunter_wind_walk-shard.png'),
('11','shuriken-toss-scepter-ability-upgrade','images/heroes/bounty_hunter/bounty_hunter_shuriken_toss-scepter.png'),
('12','thunder-clap','images/heroes/brewmaster/brewmaster_thunder_clap.png'),
('12','cinder-brew','images/heroes/brewmaster/brewmaster_cinder_brew.png'),
('12','drunken-brawler','images/heroes/brewmaster/brewmaster_drunken_brawler.png'),
('12','primal-split','images/heroes/brewmaster/brewmaster_primal_split.png'),
('12','primal-split-shard-ability-upgrade','images/heroes/brewmaster/brewmaster_primal_split-shard.png'),
('12','primal-split-scepter-ability-upgrade','images/heroes/brewmaster/brewmaster_primal_split-scepter.png'),
('13','viscous-nasal-goo','images/heroes/bristleback/bristleback_viscous_nasal_goo.png'),
('13','quill-spray','images/heroes/bristleback/bristleback_quill_spray.png'),
('13','bristleback','images/heroes/bristleback/bristleback_bristleback.png'),
('13','warpath','images/heroes/bristleback/bristleback_warpath.png'),
('13','hairball','images/heroes/bristleback/bristleback_hairball.png'),
('13','viscous-nasal-goo-scepter-ability-upgrade','images/heroes/bristleback/bristleback_viscous_nasal_goo-scepter.png'),
('14','insatiable-hunger','images/heroes/broodmother/broodmother_insatiable_hunger.png'),
('14','spin-web','images/heroes/broodmother/broodmother_spin_web.png'),
('14','silken-bola','images/heroes/broodmother/broodmother_silken_bola.png'),
('14','spawn-spiderlings','images/heroes/broodmother/broodmother_spawn_spiderlings.png'),
('14','silken-bola-shard-ability-upgrade','images/heroes/broodmother/broodmother_silken_bola-shard.png'),
('14',"spinner's-snare",'images/heroes/broodmother/broodmother_sticky_snare.png'),
('15','hoof-stomp','images/heroes/centaur_warrunner/centaur_hoof_stomp.png'),
('15','double-edge','images/heroes/centaur_warrunner/centaur_double_edge.png'),
('15','retaliate','images/heroes/centaur_warrunner/centaur_return.png'),
('15','stampede','images/heroes/centaur_warrunner/centaur_stampede.png'),
('15','double-edge-shard-ability-upgrade','images/heroes/centaur_warrunner/centaur_double_edge-shard.png'),
('15','stampede-scepter-ability-upgrade','images/heroes/centaur_warrunner/centaur_stampede-scepter.png'),
('15','chaos-bolt','images/heroes/chaos_knight/chaos_knight_chaos_bolt.png'),
('15','reality-rift','images/heroes/chaos_knight/chaos_knight_reality_rift.png'),
('15','chaos-strike','images/heroes/chaos_knight/chaos_knight_chaos_strike.png'),
('15','phantasm','images/heroes/chaos_knight/chaos_knight_phantasm.png'),
('15','chaos-bolt-shard-ability-upgrade','images/heroes/chaos_knight/chaos_knight_chaos_bolt-shard.png'),
('15','phantasm-scepter-ability-upgrade','images/heroes/chaos_knight/chaos_knight_phantasm-scepter.png');

INSERT INTO DotaBaseDB.Users (Username, UserPassword)
VALUES
('test', 'test'),
('test2', 'test2'),
('test3', 'test3'),
('test4', 'test4'),
('test5', 'test5'),
('test6', 'test6');

INSERT INTO DotaBaseDB.CountersTo (HeroID, UserID, CounterUserInfo, CounterTag)
VALUES
('2', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','Alchemist'),
('4', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','Anti-Mage');

INSERT INTO DotaBaseDB.CounteredBy (HeroID, UserID, CounteredUserInfo, CounteredTag)
VALUES
('6', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Abaddon');

INSERT INTO DotaBaseDB.HeroItemsFor (ItemID, UserID, HeroItemForUserInfo, ItemForTag)
VALUES
('3', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Abaddon');

INSERT INTO DotaBaseDB.HeroItemsAgainst (ItemID, UserID, HeroItemAgainstUserInfo, ItemAgainstTag)
VALUES
('3', '1', 'is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Alchemist');
